### ISSUE TITLE
what's the difference between cython and py2sec?

### ISSUE THREAD

**Issue by longqzh** [cckuailong/py2sec#8]
Hi.  What's the difference between cython and py2sec? And do you have a plan to contribute the upstream(cython)?

**Comment by cckuailong** [comment]
Thx for a question. Py2sec depends on Cython, and Cython is the kernal of the encryption. Py2sec is the upper application, which we can use to encrypt the .py file  or the python project easier and more convinient. We do not need to learn how to write a build file which is necessary for Cython.

Since Py2sec is an upper application, it doesn't achieve the inner of the Cython code.

**Comment by longqzh** [comment]
thx
